org: prakashjaiswal
app: aws-serverless-portfolio
service: aws-serverless-portfolio
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
